# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_DEV }}
  IMAGE: hotdog-nengazyo


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY_DEV }}
          project_id: ${{ env.PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker

#      - uses: actions/setup-node@v3
#        with:
#          node-version: '16'
#          cache: npm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        id: build-image
        with:
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: Build image
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

      - id: "deploy"
        if: github.ref == 'refs/heads/master'
        run : |
          gcloud run deploy $IMAGE \
                --image gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
                --port 80 \
                --project $PROJECT_ID \
                --region asia-northeast1 \
                --platform=managed \
                --allow-unauthenticated \
                --max-instances 10 \
                --memory 512Mi \
                --timeout 30
